version: '3'

volumes:
  db_volume:

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/root/src
    command: mvn clean spring-boot:run
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - db
  db:
    image: postgres:9.6.24
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - $PWD/db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres